"""Initial Deployment

Revision ID: 1c7a082c29f0
Revises: 
Create Date: 2022-12-01 13:58:08.819347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c7a082c29f0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('architecture', sa.Text(), nullable=False),
    sa.Column('file_type', sa.Text(), nullable=False),
    sa.Column('imports', sa.Integer(), nullable=False),
    sa.Column('exports', sa.Integer(), nullable=False),
    sa.Column('length', sa.Integer(), nullable=False),
    sa.Column('hash', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_files_metadata_hash'), 'files_metadata', ['hash'], unique=True)
    op.create_index(op.f('ix_files_metadata_id'), 'files_metadata', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_files_metadata_id'), table_name='files_metadata')
    op.drop_index(op.f('ix_files_metadata_hash'), table_name='files_metadata')
    op.drop_table('files_metadata')
    # ### end Alembic commands ###
